### ISSUE TITLE
Amazing！！

### ISSUE THREAD

**Issue by sauceplus** [1049451037/Webpage_Text_Extraction#1]
Hai! Could you tell me whether the detail of this project have a introduction?

**Comment by sauceplus** [comment]
in fact, i want to know the meaning of 'pval'.

**Comment by 1049451037** [comment]
Hi, you can check this paper: https://www.atlantis-press.com/article/25879232.pdf

**Comment by sauceplus** [comment]
Thank you for your generous offer!
